DROP TABLE LOG_CONNECT;
DROP SEQUENCE LOG_CONNECT_SEQ;

/* LOG_CONNECT  */
CREATE TABLE LOG_CONNECT(
LOG_ID VARCHAR2(50) CONSTRAINT LOG_ID_PK PRIMARY KEY,
LOG_TYPE CHAR(1), /* 0 정상로그인 1 정상 로그아웃 2 로그인 실패*/
MEM_CODE VARCHAR2(50),
MEM_ID VARCHAR2(30),
MEM_NAME VARCHAR2(30),
MEM_IP VARCHAR2(50),
LOG_DATE DATE
);

CREATE SEQUENCE LOG_CONNECT_SEQ
increment by 1
start with 1;